changelog:
  exclude:
    authors:
      - octocat
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug fix
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - miscellaneous
