on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Trim git tag for image tag
        id: tag_trimmed
        shell: bash
        env:
          TAG: ${{ github.ref_name }}
        run: echo "::set-output name=semvertag::${TAG:1}"

      - name: Build and push site generator
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/rdfpub/generator:${{ steps.tag_trimmed.outputs.semvertag }}
            ghcr.io/rdfpub/generator:latest

      - name: Create release for new version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
